language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.22"
  - "5.18"
  - "5.12"
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y build-essential
  - cpanm LWP::UserAgent
script: "perl tii.pl"